message-lists:
  - '&4感谢使用SimpleAutoMessage1'
  - '&5感谢使用SimpleAutoMessage2'
  - '&6感谢使用SimpleAutoMessage3'
  - '&d感谢使用SimpleAutoMessage4'
Time: 5
bossbar:
  - '感谢使用SimpleAutoMessage1'
  - '&5感谢使用SimpleAutoMessage2'
Bossbar-Time: 5